#!/bin/sh
# just to silence the output. shell needs to support functions 
silent_pushd() { pushd "$@" >/dev/null; }
silent_popd() { popd "$@" >/dev/null; }


# TODO: better way of defaulting xdg paths. we assume they exist under our environment
if [ -e ${XDG_DATA_HOME:-$HOME/.local/share}/force_xdg/xdg_paths ]; then
	. ${XDG_DATA_HOME:-$HOME/.local/share}/force_xdg/xdg_paths
else
	. ./xdg_paths
fi

silent_pushd "${XDG_DATA_HOME}/force_xdg"
	# for app in data_home/force_xdg/env.d/*; do
	grep --invert-match '^[[:space:]]\{0,\}#' "${XDG_CONFIG_HOME}/force_xdg/active" | \
		while IFS= read -r app; do
			. ${XDG_DATA_HOME}/force_xdg/data_home/force_xdg/env.d/${app}
		done 
silent_popd
