#!/bin/sh
if [ -e ${XDG_DATA_HOME:-$HOME/.local/share}/force_xdg/xdg_paths ]; then
	. ${XDG_DATA_HOME:-$HOME/.local/share}/force_xdg/xdg_paths
else
	. ./xdg_paths
fi

# zsh
export ZDOTDIR=${ZDOTDIR:-${XDG_CONFIG_HOME}/zsh}

# XDG Base directory fixes for pseudo-compatible programs
export XAUTHORITY="${XDG_RUNTIME_DIR}"/Xauthority
export BASH_COMPLETION_USER_FILE="${XDG_CONFIG_HOME}"/bash-completion/bash_completion

# wget-hsts for tracking downloaded files, defaults to $HOME/.wget-hsts. dumb
export WGETRC=${XDG_CONFIG_HOME}/wget/config

# zoom
export SSB_HOME="${XDG_DATA_HOME}"/zoom
# swaywm
export SWAY_CONFIG_HOME="${XDG_CONFIG_HOME}"/sway

# postgresql
export PSQLRC="${XDG_CONFIG_HOME}"/pg/psqlrc
export PSQL_HISTORY="${XDG_CACHE_HOME}"/pg/psql_history
export PGPASSFILE="${XDG_CONFIG_HOME}"/pg/pgpass
export PGSERVICEFILE="${XDG_CONFIG_HOME}"/pg/pg_service.conf

# anaconda
export CONDARC="${XDG_CONFIG_HOME}"/conda/condarc

# pass
export PASSWORD_STORE_DIR="${XDG_DATA_HOME}"/pass
# mplayer
export MPLAYER_HOME="${XDG_CONFIG_HOME}"/mplayer
# ffmpeg, note that "data" here is usually preset arguments
export FFMPEG_DATADIR="${XDG_CONFIG_HOME}"/ffmpeg

# gnupg
export GNUPGHOME="${XDG_DATA_HOME}"/gnupg
# less
export LESSHISTFILE="${XDG_STATE_HOME}"/less/history

# python
export PYTHONSTARTUP="${XDG_CONFIG_HOME}"/python/pythonrc
# rust
export CARGO_HOME=${XDG_DATA_HOME}/cargo
# go
export GOPATH="${XDG_DATA_HOME}"/go

# move perl out of home, perhaps buggy?
PERL_BASE=${XDG_DATA_HOME}/perl
export PERL_MM_OPT="INSTALL_BASE=$PERL_BASE"
export PERL_MB_OPT="--install_base $PERL_BASE"
export PATH="$PERL_BASE/bin${PATH:+:$PATH}"
export PERL5LIB="$PERL_BASE/lib/perl5"
export MANPATH="$PERL_BASE/man${MANPATH:+:$MANPATH}"

