#!/bin/sh
export EM_CONFIG="${EM_CONFIG:-${XDG_CONFIG_HOME:?}/emscripten/config}"
export EM_CACHE="${EM_CACHE:-${XDG_CACHE_HOME:?}/emscripten/cache}"
export EM_PORTS="${EM_PORTS:-${XDG_DATA_HOME:?}/emscripten/cache}"

# TODO: is this alias/function necessary?
# emcc --em-config "$XDG_CONFIG_HOME"/emscripten/config --em-cache "$XDG_CACHE_HOME"/emscripten/cache
