#!/bin/sh

# TODO: what's the difference between these?
export IPYTHONDIR="${IPYTHONDIR:-${XDG_CONFIG_HOME:?}/jupyter}"
export JUPYTER_CONFIG_DIR="${JUPYTER_CONFIG_DIR:-${XDG_CONFIG_HOME:?}/jupyter}"

