#!/bin/sh
export LEIN_HOME="${LEIN_HOME:-${XDG_DATA_HOME:?}/leiningen}"

# TODO: add the following to profiles.clj because of .m2 directory
# {:user {:local-repo #=(eval (str (System/getenv "XDG_CACHE_HOME") "/m2"))
#         :repositories  {"local" {:url #=(eval (str "file://" (System/getenv "XDG_DATA_HOME") "/m2"))
#                                  :releases {:checksum :ignore}}}
#        }}
